name: Daily Job Scan

on:
  schedule:
    - cron: "00 07 * * 1-5"   # 12:30 PM IST
  workflow_dispatch:

jobs:
  run-job-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run job scanner
        env:
          ADZUNA_APP_ID: ${{ secrets.ADZUNA_APP_ID }}
          ADZUNA_APP_KEY: ${{ secrets.ADZUNA_APP_KEY }}
        run: |
          mkdir -p outputs
          python job_scan.py



      - name: Upload outputs
        uses: actions/upload-artifact@v4
        with:
          name: job-scan-output
          path: outputs/
